---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: custom-image
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/secureblue/silverblue-main-hardened
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: rpm-ostree
    install:
      - papirus-icon-theme
      - overpass-fonts
    remove:
      - bluez-cups
      - braille-printer-app
      - cups
      - cups-browsed
      - cups-client
      - cups-filters
      - cups-filters-driverless
      - cups-ipptool
      - gnome-software
      - gutenprint
      - gutenprint-cups
      - hplip
      - hplip-libs
      - libcupsfilters
      - libppd
      - libsane-hpaio
      - sane-airscan
      - sane-backends
      - sane-backends-drivers-cameras
      - sane-backends-drivers-scanners
      - sane-backends-libs
      - epiphany-runtime
      - evince-thumbnailer
      - evince-previewer
      - evince-djvu
      - evince-libs
      - ntfs-3g
      - ntfs-3g-libs
      - ntfs-3g-system-compression
      - ntfsprogs
      - ModemManager
      - mozilla-filesystem
      - gnome-browser-connector
      - NetworkManager-wwan
      - NetworkManager-vpnc-gnome
      - NetworkManager-vpnc
      - NetworkManager-ssh
      - NetworkManager-ssh-gnome
      - NetworkManager-pptp-gnome
      - NetworkManager-pptp
      - NetworkManager-ppp
      - NetworkManager-openconnect
      - NetworkManager-openconnect-gnome
      - NetworkManager-bluetooth
      - NetworkManager-adsl
      - antiword
      - apr
      - apr-util
      - apr-util-openssl
      - apr-util-lmdb
      - avahi-tools
      - avahi-gobject
      - bluez-obexd
      - bluez
      - gnome-bluetooth
      - spice-webdavd
      - httpd-tools
      - liblouisutdml-utils
      - spice-vdagent
      - ibus-typing-booster
      - fprintd
      - fprintd-pam
      - fuse-libs
      - fuse-overlayfs
      - gamemode 
      - system-config-printer-udev
      - system-config-printer-libs
      - sssd-kcm 
      - sssd-krb5-common
      - sssd-nfs-idmap 
      - sssd-client
      - sshpass
      - qemu-guest-agent 
      - qemu-user-static-aarch64 
      - sssd-common
      - gnome-epub-thumbnailer
      - malcontent-control
      - malcontent-ui-libs
      - lvm2
      - lvm2-libs
      - hyperv-daemons
      - hyperv-daemons-license
      - hypervfcopyd
      - hypervkvpd
      - hypervvssd
      - hfsplus-tools
      - hplip-common
      - httpd-filesystem
      - rygel
      - gupnp-av
      - gupnp-dlna
      - gvfs-afc
      - gvfs-afp
      - gvfs-archive
      - gvfs-fuse
      - gvfs-gphoto2
      - gvfs-mtp
      - gvfs-smb

      
  - type: fonts
    fonts:
      google-fonts:
        - Inter
        - Raleway
        - Roboto
        - Montserrat
        - Open Sans
  - type: script
    scripts:
      - disableservices.sh
  - type: signing # this sets up the proper policy & signing files for signed images to work fully

