name: custom-image

description: This is my personal OS image.

base-image: ghcr.io/secureblue/silverblue-main-hardened
image-version: 41

modules:
  - type: rpm-ostree
    remove:
      - gvfs-afc
      - gvfs-gphoto2 
      - gvfs-mtp
      - bluez
      - bluez-libs
      - bluez-obexd
      - bluez-cups
      - cups
      - cups-filters
      - cups-filters-driverless
      - cups-browsed
      - gutenprint-cups
      - gutenprint-libs
      - gutenprint
      - braille-printer-app
      - system-config-printer-udev
      - ghostscript-tools-printing
      - ghostscript-tools-fonts
      - ghostscript
      - system-config-printer-libs
      - NetworkManager-bluetooth
      - gnome-bluetooth
      - gnome-bluetooth-libs
      - NetworkManager-ppp
      - NetworkManager-adsl
      - NetworkManager-pptp-gnome
      - NetworkManager-openconnect-gnome
      - NetworkManager-vpnc-gnome
      - NetworkManager-ssh-gnome
      - NetworkManager-ssh
      - NetworkManager-wwan
      - NetworkManager-vpnc
      - NetworkManager-pptp
      - NetworkManager-openconnect
      - libavif
      - evince-thumbnailer
      - gdk-pixbuf2
      - gnome-epub-thumbnailer
      - libgsf
      - libheif
      - libjxl
      - rsvg-pixbuf-loader
      - webp-pixbuf-loader
      - switcheroo-control
      - mcelog
      - mdadm
      - low-memory-monitor
      - uresourced
      - virtualbox-guest-additions
      - open-vm-tools
      - open-vm-tools-desktop
      - ibus-gtk3
      - ibus-libs
      - ibus-anthy-python
      - ibus-anthy
      - ibus-hangul
      - ibus-libpinyin
      - ibus-m17n
      - ibus-typing-booster
      - ibus-chewing
      - ibus-gtk4
      - at-spi2-core
      - epiphany-runtime
      - gnome-software

  - type: script
    scripts:
      - disableservices.sh